---
- name: remove old, failing config
  lineinfile:
    name: "/etc/apt/sources.list.d/pgdg.list"
    line: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    state: absent

- name: remove old apt source without valid key
  lineinfile:
    name: "/etc/apt/sources.list.d/apt_datadoghq_com.list"
    line: "deb https://apt.datadoghq.com/ stable 6"
    state: absent

- name: remove current apt source
  file:
    path: "/etc/apt/sources.list.d/ansible_datadog_7.list"
    state: absent

- name: remove datadog package
  apt:
    name: datadog-agent
    state: absent
    autoremove: yes

- name: remove datadog keys package
  apt:
    name: datadog-signing-keys
    state: absent
    autoremove: yes

- name: set up postgres stats collection
  import_tasks: pg_stats.yml
  when: datadog_key is defined and datadog_db_password is defined

- name: set up nginx stats collection
  import_tasks: nginx_stats.yml
  when: datadog_key is defined
