---
- name: remove nginx stub_status
  file:
    path: /etc/nginx/conf.d/status.conf
    state: absent
  become: yes
  notify:
    - reload nginx

- name: remove datadog nginx integration
  file:
    path: /etc/datadog-agent/conf.d/nginx.d/conf.yaml
    state: absent
  become: true
