---
- name: remove postgres stats configuration
  file:
    path: "{{ postgresql_config_path }}/conf.d/stats.conf"
    state: absent
  become: yes
  notify: restart postgres

- name: remove postgres logging configuration
  file:
    dest: "{{ postgresql_config_path }}/conf.d/logging.conf"
    state: absent
  become: yes
  notify: restart postgres

- name: remove datadog postgres integration
  file:
    dest: /etc/datadog-agent/conf.d/postgres.d/conf.yaml
    state: absent
  become: true

- name: remove pg_stat_activity_dd view
  command: "psql {{ db }} -c 'DROP VIEW IF EXISTS pg_stat_activity_dd;'"
  become: yes
  become_user: postgres
  notify: restart postgres

- name: remove pg_stat_activity function
  command: "psql {{ db }} -c 'DROP FUNCTION IF EXISTS pg_stat_activity();'"
  become: yes
  become_user: postgres
  notify: restart postgres
