---
# Ensure the database is created, migrated and seeded (first deployment only)

- name: load database schema
  command: bash -lc "bundle exec rake db:schema:load RAILS_ENV={{ rails_env }} I_AM_SURE=1"
  args:
    chdir: "{{ build_path }}"
  tags:
    - rake
    - skip_ansible_lint

- name: migrate database
  command: bash -lc "bundle exec rake db:migrate RAILS_ENV={{ rails_env }}"
  args:
    chdir: "{{ build_path }}"
  tags:
    - rake
    - skip_ansible_lint
  notify: restart puma

- name: seed database
  command: bash -lc "bundle exec rake db:seed RAILS_ENV={{ rails_env }}"
  args:
    chdir: "{{ build_path }}"
  tags:
    - seed
    - skip_ansible_lint
  notify: restart puma
