rails_env: "staging"

ssl_certificate: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
ssl_certificate_key:  "/etc/ssl/private/ssl-cert-snakeoil.key"

# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Australia
country_code: AU
currency: AUD
locale: en
language: en_AU.UTF-8
language_packages:
  - language-pack-en-base
l10n_repo: https://github.com/openfoodfoundation/l10n_au.git
timezone: Melbourne

developer_email: admin@example.com

users_sysadmin:
  - "{{ core_devs }}"

# Test host configuration
# This is usually set in the host config but the same for all local containers.
domain: localhost

admin_email: ofn@example.com
mail_domain: example.com

# Add missing vars to emulate /local_vagrant/secrets.yml
db_password: 'f00d'
admin_password: 'ofn123'
secret_token: '511a3d0fa1551b9fa75a1aef5b47684905c64807963fa2c190272878366365'
google_maps_api_key: 'xxx'

mail_host: 'example.com'
mail_port: 25
smtp_username: 'admin'
smtp_password: 'password'
